type LanguageData = {
    [key: string]: string;
  };


  const everyRoom: LanguageData = {
   door: 'porta',
    light: 'leggero (masculine) or leggera (feminine)',
    desk: 'scrivania',
    mirror: 'specchio',
    wardrobe: 'armadio',
    chair: 'sedia',
    watch: 'orologio',
    bed: 'letto (masculine) or letta (feminine)',
    laptop: 'computer portatile',
    phone: 'telefono',
    'side table': 'tavolino',
    jacket: 'giacca',
    clothes: 'vestiti',
  };
  const myRoom: LanguageData ={
    journal: 'rivista',
    box: 'scatola',
    pen: 'penna',
    slider: 'cursore',
    shoes: 'scarpe',
    'washing basket': 'cesto per il lavaggio',
    monster: 'mostro',
    timer: 'timer',
    'side table': 'tavolino',
  };
  const numberDate: LanguageData = {
    1: 'uno',
    2: 'due',
    3: 'tre',
    4: 'quattro',
    5: 'cinque',
    6: 'sei',
    7: 'sette',
    8: 'otto',
    9: 'nove',
    10: 'dieci',
    11: 'undici',
    12: 'dodici',
    13: 'tredici',
    14: 'quattordici',
    15: 'quindici',
    16: 'sedici',
    17: 'diciassette',
    18: 'diciotto',
    19: 'diciannove',
    20: 'venti',
    21: 'ventuno',
    22: 'ventidue',
    23: 'ventitré',
    24: 'ventiquattro',
    25: 'venticinque',
    26: 'ventisei',
    27: 'ventisette',
    28: 'ventotto',
    29: 'ventinove',
    30: 'trenta',
    31: 'trentuno',
    32: 'trentadue',
    33: 'trentatré',
    34: 'trentaquattro',
    35: 'trentacinque',
    36: 'trentasei',
    37: 'trentasette',
    38: 'trentotto',
    39: 'trentanove',
    40: 'quaranta',
    41: 'quarantuno',
    42: 'quarantadue',
    43: 'quarantatré',
    44: 'quarantaquattro',
    45: 'quarantacinque',
    46: 'quarantasei',
    47: 'quarantasette',
    48: 'quarantotto',
    49: 'quarantanove',
    50: 'cinquanta',
    51: 'cinquantuno',
    52: 'cinquantadue',
    53: 'cinquantatré',
    54: 'cinquantaquattro',
    55: 'cinquantacinque',
    56: 'cinquantasei',
    57: 'cinquantasette',
    58: 'cinquantotto',
    59: 'cinquantanove',
    60: 'sessanta',
    61: 'sessantuno',
    62: 'sessantadue',
    63: 'sessantatré',
    64: 'sessantaquattro',
    65: 'sessantacinque',
    66: 'sessantasei',
    67: 'sessantasette',
    68: 'sessantotto',
    69: 'sessantanove',
    70: 'settanta',
    71: 'settantuno',
    72: 'settantadue',
    73: 'settantatré',
    74: 'setantaquattro',
    75: 'settantacinque',
    76: 'settantasei',
    77: 'settantasette',
    78: 'settantotto',
    79: 'settantanove',
    80: 'ottanta',
    81: 'ottantuno',
    82: 'ottantadue',
    83: 'ottantatré',
    84: 'ottantaquattro',
    85: 'ottantacinque',
    86: 'ottantasei',
    87: 'ottantasette',
    88: 'ottantotto',
    89: 'ottantanove',
    90: 'novanta',
    91: 'novantuno',
    92: 'novantadue',
    93: 'novantatré',
    94: 'novantaquattro',
    95: 'novantacinque',
    96: 'novantasei',
    97: 'novantasette',
    98: 'novantotto',
    99: 'novantanove',
    100: 'cento'
  };
  const dayOfTheWeek : LanguageData = {
    Monday: 'Lunedì',
    Tuesday: 'Martedì',
    Wednesday: 'Mercoledì',
    Thursday: 'Giovedì',
    Friday: 'Venerdì',
    Saturday: 'Sabato',
    Sunday: 'Domenica',
  };
  const session : LanguageData = {
    January: 'Gennaio',
    February: 'Febbraio',
    March: 'Marzo',
    April: 'aprile',
    May: 'Maggio',
    June: 'giugno',
    July: 'luglio',
    August: 'agosto',
    September: 'settembre',
    October: 'ottobre',
    November: 'novembre',
    December: 'dicembre',
    wallet: 'portafoglio',
    summer: 'estate',
    spring: 'primavera',
    autumn: 'autunno',
    winter: 'inverno',
  };
  const conrolingTime : LanguageData = {
    'quarter to': 'meno un quarto',
    'quarter past': 'passaggio di un quarto',
    half: 'avavo',
    next: 'prossimo (masculine) or prossima (feminine)',
    last: 'scorso (masculine) or scorsa (feminine)',
    firstly: 'in primo luogo',
    secondly: 'in secondo luogo',
    yesterday: 'Ieri',
    tomorrow: 'Domani',
    now: 'Ora',
    later: 'Dopo',
    earlier: 'prima',
  };
  const allLanguageData: { [key: string]: LanguageData } = {
    spaceContorl,
    everyRoom,
    myRoom,
    numberDate,
    dayOfTheWeek,
    session,
    conrolingTime,
  };
  export default allLanguageData;